name = ["Bob", "Karen", "Mike", "Cela", "Sam", "Bob", "Bob"]
luckyNumbers = [2, 6, 55, 21, 12, 90, 34]
print("!!!!!")
name.sort()
luckyNumbers.sort()
print(name)
print(luckyNumbers)
luckyNumbers.reverse()
print(luckyNumbers)
print("!!!!!")

name2 = name.copy()
print(name2)
print("@!@!@!@!")
name[1] = "Qba"
print(name[1])
print(name)
luckyNumbers.append(99)
print("append doaje do listy na jej koniec")
print(luckyNumbers)
luckyNumbers.insert(0, 101)
print("insert pzekazujesz dwie warosci 1 (miejsce w tabeli) , 2 wartosc dodania")
print(luckyNumbers)
liczba = 25
luckyNumbers.remove(99)
print(luckyNumbers)
luckyNumbers.clear()
print(luckyNumbers)
name.pop()
print(str(name) + " pop usuwa ostatnia pozycje z listy")
print(str(name.index("Cela")) + " pokazuje na którym miejscu listy jest to czego szukamy")
print()
print(name.count("Bob"))
print("bob " + str(liczba))

print(name.sort())
print(" sort układa wg kolejnosci alfabetycznej")
name.extend(luckyNumbers)
print(name)